name: Deploy Server to Elastic Beanstalk

on:
  push:
    branches: [ main ]
    paths:
      - 'FlightFinder.Server/**'
      - 'FlightFinder.Shared/**'
      - '.github/workflows/server-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EB_APP: ${{ secrets.EB_APP }}
      EB_ENV: ${{ secrets.EB_ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "FlightFinder.Server/FlightFinder.Server.csproj"

      - name: Publish
        run: dotnet publish "FlightFinder.Server/FlightFinder.Server.csproj" -c Release -r linux-x64 -o publish --self-contained false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActionsServerDeploy
        if: ${{ secrets.AWS_ROLE_ARN != '' }}

      - name: Configure AWS Credentials (access keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: ${{ secrets.AWS_ROLE_ARN == '' }}

      - name: Install EB CLI
        run: pip install awsebcli --upgrade

      - name: Zip artifact
        run: |
          cd publish
          powershell -Command "Compress-Archive -Path * -DestinationPath ..\server.zip"

      - name: Deploy to EB
        run: |
          eb init "${{ env.EB_APP }}" --region "${{ env.AWS_REGION }}" --platform ".NET Core on Linux"
          eb use "${{ env.EB_ENV }}"
          eb deploy --staged
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        working-directory: publish
